version: "2"
services:
  flask_app:
    image: bruno128/oficina-flask:latest
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:8.0.35
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro